baseURL: "https://miqbalsamudra.netlify.app/"
languageCode: "en-us"
title: "My Portfolio"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  # main:
  #   - identifier: blog
  #     name: Blog
  #     title: Blog posts
  #     url: /blogs
  #     weight: 1
  #   - identifier: gallery
  #     name: Gallery
  #     title: Blog posts
  #     url: /gallery
  #     weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "My Portfolio"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"
  
  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    defaultTheme: "dark" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "My Portfolio" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "M Iqbal Samudra."
    subtitle: "Coding makes me happy"
    content: "A boy with his enthusiasm for IT, including networking and programming."
    image: /images/hero.jpg
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "https://drive.google.com/file/d/14j22HU0i_hHGccX5xjPlQKv-DJKVdFnt/view?usp=sharing"
      download: true
      newPage: true
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/samudraiqbal
        - icon: fab fa-linkedin-in
          url: https://www.linkedin.com/in/miqbalsamudra/
        - icon: fa-solid fa-envelope
          url: mailto:miqbalsamudra@gmail.com

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me.jpg"
    content: |-
      A graduate of BINUS University with a major in Information Systems, I have nearly 5 years of experience working in the field of networking.

      I am currently focusing on programming because I want to develop the skills I pursued during my studies at SMK Telkom Malang in Software Engineering.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "HTML"
        - "CSS"
        - "JavaScript"
        - "Node.JS"
        - "Java"
        - "Kotlin"
        - "MySQL"
        - "Katalon Studio"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Project Controller FTTH"
        company: "PT Aplikanusa Lintasarta"
        companyUrl: "https://www.lintasarta.net/"
        date: "Jun 2022 - Sep 2023"
        featuredLink:
          enable: false
        content: |
          - Monitoring vendors to ensure the project proceeds according to plan
          - Providing solutions for utility installation issues in the field
          - Coordinating with internal stakeholders regarding network device installation points

      - job: "Project Design FTTH"
        company: "PT Link Net Tbk"
        companyUrl: "https://www.linknet.co.id/"
        date: "Oct 2021 - Sep 2021"
        featuredLink:
          enable: false
        content: |
          - Creating network cable construction designs according to survey results
          - Making recommendations for migration construction drawings, both aerial and underground types, as guidance for the field construction team
          - Reporting daily activity

      - job: "Provisioning Technician WIBS"
        company: "PT Telkom Akses"
        companyUrl: "https://telkomakses.co.id/"
        date: "Dec 2020 - Oct 2021"
        featuredLink:
          enable: false
        content: |
          - Conducting surveys and installing fiber optic networks for services used by other vendor customers
          - Performing patchcord jumpers in the Datacenter
          
      - job: "Helpdesk Provisioning & Migration"
        company: "PT Telkom Akses"
        companyUrl: "https://telkomakses.co.id/"
        date: "Jun 2020 - Nov 2020"
        featuredLink:
          enable: false
        content: |
          - Monitoring order tickets to ensure no orders are delayed due to system issues
          - Assisting field technicians in activating internet, voice, and UseeTV services
          
      - job: "Surveyor"
        company: "PT Telkom Akses"
        companyUrl: "https://telkomakses.co.id/"
        date: "Oct 2021 - Sep 2021"
        featuredLink:
          enable: false
        content: |
          - Conducting surveys for the construction of new FTTx networks both on desk and on site
          - Surveying existing fiber optic networks
          - Planning and designing the development of new FTTx networks using Google Earth along with the budget allocation
      
  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Bachelor's Degree in Information Systems"
        school:
          name: "BINUS University"
          url: "https://binus.ac.id/"
        date: "2019 - 2022"
        GPA: "3.74 out of 4.0"
        # content: |-
        #   Extracurricular Activities
        #     - Lorem ipsum dolor sit amet consectetur adipisicing elit. 
        #     - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
        featuredLink:
          enable: true
          name: "My graduate certificate"
          url: "https://drive.google.com/file/d/1gkLlrcuvgdPxOx426mrPhpVCjmB-b9yD/view?usp=sharing"
      - title: "Software Engineering"
        school:
          name: "SMK Telkom Malang"
          url: "https://www.smktelkom-mlg.sch.id/"
        date: "2015 - 2018"
        GPA: "31.65 out of 40.0"
        # content: |-
        #   I Publiced two papers in the ACM SIGCHI Conference on Artificial Intelligence.
        #   - [Fast and Accurate Object Detection with a Single Convolutional Neural Network](https://example.com)
        #   - Face mask detection using a single convolutional neural network.

        #   Extracurricular Activities
        #     - Lorem ipsum dolor sit amet consectetur adipisicing elit. 
        #     - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
        featuredLink:
          enable: true
          name: "My graduate certificate"
          url: "https://drive.google.com/file/d/1EAmddh5hHKLJiv1BBaRC5PSy-1AfmL_A/view?usp=sharing"

  # Achievements
  achievements:
    enable: true
    title: "Certificates"
    items:
      - title: Coding.ID
        content: Bootcamp Quality Assurance Engineer
        url: https://coding.id/report/xLYW35oy
        image: /images/codingid.jpg
      - title: Baparekraf Digital Talent Tahun 2022
        content: Android Developer Dasar
        url: https://drive.google.com/file/d/1qnQ6zkMymw5Y84AuwFYQAH5xh7b8t8fD/view?usp=sharing
        image: /images/bdd.jpg
      - title: Dicoding Academy
        content: Belajar Membuat Aplikasi Android untuk Pemula
        url: https://www.dicoding.com/certificates/JLX1L2GKGX72
        image: /images/dicoding.jpg
      - title: Dicoding Academy
        content: Memulai Pemrograman Dengan Kotlin
        url: https://www.dicoding.com/certificates/81P2835YQPOY
        image: /images/dicoding.jpg
      - title: Dicoding Academy
        content: Belajar Dasar Pemrograman JavaScript
        url: https://www.dicoding.com/certificates/0LZ01W79QP65
        image: /images/dicoding.jpg
      - title: Dicoding Academy
        content: Belajar Dasar Pemrograman Web
        url: https://www.dicoding.com/certificates/1RXYOYQ59PVM
        image: /images/dicoding.jpg
      - title: Dicoding Academy
        content: Belajar Membuat Front-End Web untuk Pemula
        url: https://www.dicoding.com/certificates/EYX4927O6PDL
        image: /images/dicoding.jpg

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Mudah Sukses Mandiri
        content: Landing page of the "Mudah Sukses Mandiri" website about selling building materials.
        image: /images/projects/mudahsuksesmandiri.png
        featured:
          name: Demo
          link: https://mudahsuksesmandiri.xyz/
        badges:
          - "CodeIgniter 3"
          - "Bootstrap"

      - title: Untung Bahagia Abadi
        content: Landing page of the "Untung Bahagia Abadi" website about selling building materials.
        image: /images/projects/untungbahagiaabadi.png
        featured:
          name: Demo
          link: https://untungbahagiaabadi.xyz/
        badges:
          - "CodeIgniter 3"
          - "Bootstrap"

      - title: CV Inti Perkasa Networking
        content: Landing page of the "88Network" site from CV Inti Perkasa Networking about Telemarketing / Agent Recruitment.
        image: /images/projects/intinet88.png
        featured:
          name: Demo
          link: https://intinet88.xyz/
        badges:
          - "CodeIgniter 3"
          - "Bootstrap"

      - title: Citra Desain Angkasa
        content: Landing page of the "Citra Desain Angkasa" website about interior design services.
        image: /images/projects/citradesainangkasa.png
        featured:
          name: Demo
          link: https://citradesainangkasa.xyz/
        badges:
          - "CodeIgniter 3"
          - "Bootstrap"

      - title: Sehat Bahagia Bersatu
        content: Landing page of the "Sehat Bahagia Bersatu" website about selling car spare parts.
        image: /images/projects/sehatbahagiabersatu.png
        featured:
          name: Demo
          link: https://sehatbahagiabersatu.xyz/
        badges:
          - "CodeIgniter 3"
          - "Bootstrap"

      - title: Mujur Jaya Pratama
        content: Landing page of the "Mujur Jaya Pratama" website about selling ornamental plants.
        image: /images/projects/mujurjayapratama.png
        featured:
          name: Demo
          link: https://mujurjayapratama.xyz/
        badges:
          - "CodeIgniter 3"
          - "Bootstrap"

      - title: Rumah Karya Abadi
        content: Landing page of the "Rumah Karya Abadi" website about cleaning service providers.
        image: /images/projects/rumahkaryaabadi.png
        featured:
          name: Demo
          link: https://rumahkaryaabadi.com/
        badges:
          - "CodeIgniter 3"
          - "Bootstrap"

      - title: Untung Mega Sentosa
        content: Landing page of the "Untung Mega Sentosa" website about selling basic necessities.
        image: /images/projects/untungmegasentosa.png
        featured:
          name: Demo
          link: https://untungmegasentosa.com/
        badges:
          - "CodeIgniter 3"
          - "Bootstrap"

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    btnName: Mail me
    btnLink: mailto:miqbalsamudra@gmail.com
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: false
      disableFeaturedImage: false
   # socialNetworks:
      # github: https://github.com/samudraiqbal
      # linkedin: https://www.linkedin.com/in/miqbalsamudra/
      # twitter: https://twitter.com
      # instagram: https://instagram.com
      # facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
